### ISSUE TITLE
2.0 release?

### ISSUE THREAD

**Issue by a17r** [sjuvonen/coquillo#5]
Readme talks about a 2.0 release, but there does not seem to be a tarball yet? Since distributions are weeding out Qt4 everywhere, it would be a good time to make a real release now.

**Comment by sjuvonen** [comment]
Finalizing the missing stuff has been on my todo for a long time but I have not had the required mindset for finalizing this app. As of now, it isn't feature-complete and definitely not usable for most people. My intention is to work on this thing this month and maybe even get it ready. I have been neglecting it far too long. 

Thanks for notifying me that Qt 4 is phasing out.

**Comment by sjuvonen** [comment]
README was written hastily when I expected to get the app ready last fall but then it didn't happen after all. It should state the actual state of the app is more like almost-beta.

**Comment by a17r** [comment]
thanks for your quick reply!

**Comment by a17r** [comment]
Please let me know when you think it makes sense to think about packaging it, even if only for an experimental live version to test.

**Comment by sjuvonen** [comment]
Sorry, I was busy at work due to my upcoming and currently on-going vacation. I got to finalize the MusicBrainz search feature and got the impression that everything else was actually already done to the extent that '2.0' is on par with the previous releases. Next week, I think, I will be able to test the app with thought and then it should be ready to fly.

**Comment by a17r** [comment]
These lines make sure your application only builds on Debian and Arch right now:
https://github.com/sjuvonen/coquillo/blob/master/coquillo.pro#L19
https://github.com/sjuvonen/coquillo/blob/master/coquillo.pro#L23

imo the build system should follow the standard set by the upstream musicbrainz package and at most workaround downstream packaging as a fallback.

**Comment by a17r** [comment]
Also right now the old extras directory for desktop and icon files is missing ;)

**Comment by sjuvonen** [comment]
Hi. I fell ill after my vacation so my original schedule for preparing release got stretched. The basic functionality is there and works but there are some smaller bugs that should be fixed before proper stable release. But if you are in a hurry, then something like 'beta' will be okay. 

I am aware that my way of linking to musicbrainz5 excludes all other distros, but actually I wanted to do as you suggested, and fallback to one style and use the other as an override... BUT I did not know how to write a check for that (if-else structure) in the .pro file so I resorted to this temporary hack as I had to enable Debian builds for my private use. 

The previous generation of Coquillo used libcddb and there was no need to customize the linking command per-distro back then, so I have no experience in this advanced subject.

**Comment by sjuvonen** [comment]
Now I figured how to write the check so that it works with all distros.

**Comment by a17r** [comment]
thanks for that fix, not much I could contribute wrt qmake either ;)

**Comment by sjuvonen** [comment]
Hi. I decided to make a release after fixing a couple more bugs. I also updated my OBS profile in case you have been looking at it or maybe not. I will try to be a bit more thorough this time around and create tags for the releases as they come.

https://www.opendesktop.org/p/1130981/
https://software.opensuse.org//download.html?project=home%3Asjuvonen&package=coquillo

**Comment by a17r** [comment]
Thanks, now packaged in Gentoo: https://github.com/gentoo/gentoo/commit/a50c01548737f241fd650aab0fbf432730abb763
